using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using MapperForge.Generator.Models;
using MapperForge.Generator.Utilities;

namespace MapperForge.Generator.Emitting;

internal static class MappingEmitter
{
    public static string EmitDestinationMapping(MappingPlan plan)
    {
        var destination = plan.DestinationType;
        var sourceTypeName = plan.SourceType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
        var destinationTypeName = destination.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CodeDom.Compiler;");
        builder.AppendLine();

        var namespaceName = destination.ContainingNamespace.IsGlobalNamespace
            ? null
            : destination.ContainingNamespace.ToDisplayString();

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        var indent = "";
        foreach (var containingType in SymbolUtilities.GetContainingTypes(destination))
        {
            builder.Append(indent)
                .Append("partial ")
                .Append(SymbolUtilities.GetTypeKeyword(containingType))
                .Append(' ')
                .Append(containingType.Name)
                .AppendLine();
            builder.Append(indent).AppendLine("{");
            indent += "    ";
        }

        builder.Append(indent).AppendLine("[GeneratedCode(\"MapperForge\", \"0.1.0\")]");
        builder.Append(indent)
            .Append("partial ")
            .Append(SymbolUtilities.GetTypeKeyword(destination))
            .Append(' ')
            .Append(destination.Name)
            .AppendLine();
        builder.Append(indent).AppendLine("{");

        var bodyIndent = indent + "    ";
        builder.Append(bodyIndent)
            .Append("public static ")
            .Append(destinationTypeName)
            .Append(" From(")
            .Append(sourceTypeName)
            .AppendLine(" source)");
        builder.Append(bodyIndent).AppendLine("{");
        builder.Append(bodyIndent).AppendLine("    ArgumentNullException.ThrowIfNull(source);");
        builder.AppendLine();

        if (plan.Assignments.Length == 0)
        {
            builder.Append(bodyIndent).Append("    return new ").Append(destinationTypeName).AppendLine("();");
        }
        else
        {
            builder.Append(bodyIndent).Append("    return new ").Append(destinationTypeName).AppendLine();
            builder.Append(bodyIndent).AppendLine("    {");

            foreach (var assignment in plan.Assignments)
            {
                builder.Append(bodyIndent)
                    .Append("        ")
                    .Append(SymbolUtilities.EscapeIdentifier(assignment.DestinationName))
                    .Append(" = ")
                    .Append(assignment.Expression)
                    .AppendLine(",");
            }

            builder.Append(bodyIndent).AppendLine("    };");
        }

        builder.Append(bodyIndent).AppendLine("}");
        builder.Append(indent).AppendLine("}");

        foreach (var _ in SymbolUtilities.GetContainingTypes(destination))
        {
            indent = indent.Substring(0, indent.Length - 4);
            builder.Append(indent).AppendLine("}");
        }

        return builder.ToString();
    }

    public static string EmitExtensions(ImmutableArray<MappingPlan> plans)
    {
        var groupedPlans = plans
            .GroupBy(static plan => plan.SourceType, SymbolEqualityComparer.Default)
            .OrderBy(static group => group.Key!.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat))
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.CodeDom.Compiler;");
        builder.AppendLine();
        builder.AppendLine("namespace MapperForge;");
        builder.AppendLine();
        builder.AppendLine("[GeneratedCode(\"MapperForge\", \"0.1.0\")]");
        builder.AppendLine("public static partial class MapperForgeGeneratedExtensions");
        builder.AppendLine("{");

        foreach (var group in groupedPlans)
        {
            var sourceTypeName = group.Key!.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
            builder.Append("    public static TDestination MapTo<TDestination>(this ")
                .Append(sourceTypeName)
                .AppendLine(" source)");
            builder.AppendLine("    {");
            builder.AppendLine("        ArgumentNullException.ThrowIfNull(source);");
            builder.AppendLine();

            foreach (var plan in group.OrderBy(static plan => plan.DestinationType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat)))
            {
                var destinationTypeName = plan.DestinationType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
                builder.Append("        if (typeof(TDestination) == typeof(")
                    .Append(destinationTypeName)
                    .AppendLine("))");
                builder.AppendLine("        {");
                builder.Append("            return (TDestination)(object)")
                    .Append(destinationTypeName)
                    .AppendLine(".From(source);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.Append("        throw new global::MapperForge.MapperForgeMappingException($\"MapperForge could not find a generated mapping from '")
                .Append(sourceTypeName.Replace("global::", ""))
                .AppendLine("' to '{typeof(TDestination).FullName}'.\");");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.Append("    public static List<TDestination> MapToList<TDestination>(this IEnumerable<")
                .Append(sourceTypeName)
                .AppendLine("> source)");
            builder.AppendLine("    {");
            builder.AppendLine("        ArgumentNullException.ThrowIfNull(source);");
            builder.AppendLine("        var results = new List<TDestination>();");
            builder.AppendLine();
            builder.AppendLine("        foreach (var item in source)");
            builder.AppendLine("        {");
            builder.AppendLine("            results.Add(item.MapTo<TDestination>());");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        return results;");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.Append("    public static List<TDestination> MapTo<TDestination>(this IEnumerable<")
                .Append(sourceTypeName)
                .AppendLine("> source)");
            builder.AppendLine("    {");
            builder.AppendLine("        return source.MapToList<TDestination>();");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string GetHintName(MappingPlan plan)
    {
        static string Sanitize(string value)
        {
            var builder = new StringBuilder(value.Length);

            foreach (var character in value)
            {
                builder.Append(char.IsLetterOrDigit(character) ? character : '_');
            }

            return builder.ToString();
        }

        return Sanitize(plan.DestinationType.ToDisplayString()) + "_From_" + Sanitize(plan.SourceType.ToDisplayString()) + ".g.cs";
    }
}
