using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using MapperForge.Generator.Models;
using MapperForge.Generator.Utilities;

namespace MapperForge.Generator.Emitting;

internal static class MappingEmitter
{
    public static string EmitDestinationMapping(MappingPlan plan)
    {
        var destination = plan.DestinationType;
        var sourceTypeName = plan.SourceType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
        var destinationTypeName = destination.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CodeDom.Compiler;");
        builder.AppendLine();

        if (plan.MethodAccessibility == "public")
        {
            builder.Append("[assembly: global::MapperForge.MapperForgeMappingAttribute(typeof(")
                .Append(plan.SourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append("), typeof(").Append(destination.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append("), 1");
            foreach (var dependency in plan.Dependencies.OrderBy(static pair => pair.StableIdentity, System.StringComparer.Ordinal))
                builder.Append(", typeof(").Append(dependency.Source.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append("), typeof(").Append(dependency.Destination.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(')');
            builder.AppendLine(")]");
            builder.AppendLine();
        }

        var namespaceName = destination.ContainingNamespace.IsGlobalNamespace
            ? null
            : SymbolUtilities.GetNamespaceName(destination.ContainingNamespace);

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        var indent = "";
        foreach (var containingType in SymbolUtilities.GetContainingTypes(destination))
        {
            builder.Append(indent)
                .Append("partial ")
                .Append(SymbolUtilities.GetTypeKeyword(containingType))
                .Append(' ')
                .Append(SymbolUtilities.EscapeIdentifier(containingType.Name))
                .AppendLine();
            builder.Append(indent).AppendLine("{");
            indent += "    ";
        }

        builder.Append(indent)
            .Append("partial ")
            .Append(SymbolUtilities.GetTypeKeyword(destination))
            .Append(' ')
            .Append(SymbolUtilities.EscapeIdentifier(destination.Name))
            .AppendLine();
        builder.Append(indent).AppendLine("{");

        var bodyIndent = indent + "    ";
        builder.Append(bodyIndent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"MapperForge\", \"0.1.0\")]");
        builder.Append(bodyIndent)
            .Append(plan.MethodAccessibility).Append(plan.HidesInheritedFrom ? " new static " : " static ")
            .Append(destinationTypeName)
            .Append(" From(")
            .Append(sourceTypeName)
            .AppendLine(" source)");
        builder.Append(bodyIndent).AppendLine("{");
        if (plan.SourceType.IsReferenceType || NullabilityPolicy.IsNullable(plan.SourceType))
            builder.Append(bodyIndent).AppendLine("    global::System.ArgumentNullException.ThrowIfNull(source);");
        builder.AppendLine();

        if (plan.Assignments.Length == 0)
        {
            builder.Append(bodyIndent).Append("    return new ").Append(destinationTypeName).AppendLine("();");
        }
        else
        {
            builder.Append(bodyIndent).Append("    return new ").Append(destinationTypeName).AppendLine();
            builder.Append(bodyIndent).AppendLine("    {");

            foreach (var assignment in plan.Assignments)
            {
                builder.Append(bodyIndent)
                    .Append("        ")
                    .Append(SymbolUtilities.EscapeIdentifier(assignment.DestinationName))
                    .Append(" = ")
                    .Append(assignment.Expression)
                    .AppendLine(",");
            }

            builder.Append(bodyIndent).AppendLine("    };");
        }

        builder.Append(bodyIndent).AppendLine("}");
        builder.Append(indent).AppendLine("}");

        foreach (var _ in SymbolUtilities.GetContainingTypes(destination))
        {
            indent = indent.Substring(0, indent.Length - 4);
            builder.Append(indent).AppendLine("}");
        }

        return builder.ToString();
    }

    public static string EmitExtensions(ImmutableArray<MappingEntry> plans, string helperName)
    {
        var groupedPlans = plans
            .GroupBy(static plan => plan.SourceType, SymbolEqualityComparer.Default)
            .OrderBy(static group => group.Key!.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat))
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.CodeDom.Compiler;");
        builder.AppendLine();
        builder.AppendLine("namespace MapperForge;");
        builder.AppendLine();
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"MapperForge\", \"0.1.0\")]");
        builder.Append("internal static class ").AppendLine(helperName);
        builder.AppendLine("{");

        foreach (var group in groupedPlans)
        {
            var sourceTypeName = group.Key!.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
            const string accessibility = "internal";
            builder.Append("    ").Append(accessibility).Append(" static TDestination MapTo<TDestination>(this ")
                .Append(sourceTypeName)
                .AppendLine(" source)");
            builder.AppendLine("    {");
            if (((ITypeSymbol)group.Key).IsReferenceType || NullabilityPolicy.IsNullable((ITypeSymbol)group.Key))
                builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(source);");
            builder.AppendLine();

            foreach (var plan in group.OrderBy(static plan => plan.DestinationType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat)))
            {
                var destinationTypeName = plan.DestinationType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat);
                builder.Append("        if (typeof(TDestination) == typeof(")
                    .Append(destinationTypeName)
                    .AppendLine("))");
                builder.AppendLine("        {");
                builder.Append("            return (TDestination)(object)")
                    .Append('(').Append(destinationTypeName).Append(')')
                    .Append(destinationTypeName)
                    .AppendLine(".From(source);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.Append("        throw new global::MapperForge.MapperForgeMappingException($\"MapperForge could not find a generated mapping from '")
                .Append(sourceTypeName.Replace("global::", ""))
                .AppendLine("' to '{typeof(TDestination).FullName}'.\");");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.Append("    ").Append(accessibility).Append(" static global::System.Collections.Generic.List<TDestination> MapToList<TDestination>(this global::System.Collections.Generic.IEnumerable<")
                .Append(sourceTypeName)
                .AppendLine("> source)");
            builder.AppendLine("    {");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(source);");
            builder.Append("        if (");
            builder.Append(string.Join(" && ", group.Select(static plan => "typeof(TDestination) != typeof(" +
                plan.DestinationType.ToDisplayString(SymbolUtilities.FullyQualifiedNullableFormat) + ")")));
            builder.AppendLine(")");
            builder.AppendLine("        {");
            builder.Append("            throw new global::MapperForge.MapperForgeMappingException($\"MapperForge could not find a generated mapping from '")
                .Append(sourceTypeName.Replace("global::", ""))
                .AppendLine("' to '{typeof(TDestination).FullName}'.\");");
            builder.AppendLine("        }");
            builder.AppendLine("        var results = new global::System.Collections.Generic.List<TDestination>();");
            builder.AppendLine();
            builder.AppendLine("        foreach (var item in source)");
            builder.AppendLine("        {");
            builder.Append("            results.Add(global::MapperForge.").Append(helperName)
                .AppendLine(".MapTo<TDestination>(item));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        return results;");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.Append("    ").Append(accessibility).Append(" static global::System.Collections.Generic.List<TDestination> MapTo<TDestination>(this global::System.Collections.Generic.IEnumerable<")
                .Append(sourceTypeName)
                .AppendLine("> source)");
            builder.AppendLine("    {");
            builder.Append("        return global::MapperForge.").Append(helperName)
                .AppendLine(".MapToList<TDestination>(source);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string GetHintName(MappingPlan plan)
    {
        static string Sanitize(string value)
        {
            var builder = new StringBuilder(value.Length);

            foreach (var character in value)
            {
                builder.Append(char.IsLetterOrDigit(character) ? character : '_');
            }

            return builder.ToString(0, System.Math.Min(builder.Length, 80));
        }

        var identity = SymbolUtilities.GetStableTypeIdentity(plan.SourceType) + "->" +
            SymbolUtilities.GetStableTypeIdentity(plan.DestinationType);
        using var sha256 = SHA256.Create();
        var hash = string.Concat(sha256.ComputeHash(Encoding.UTF8.GetBytes(identity))
            .Select(static value => value.ToString("x2", System.Globalization.CultureInfo.InvariantCulture)));
        return Sanitize(plan.DestinationType.ToDisplayString()) + "_From_" +
            Sanitize(plan.SourceType.ToDisplayString()) + "_" + hash + ".g.cs";
    }

    public static string GetHelperName(Compilation compilation)
    {
        using var sha256 = SHA256.Create();
        var hash = string.Concat(sha256.ComputeHash(Encoding.UTF8.GetBytes(compilation.Assembly.Identity.ToString()))
            .Select(static value => value.ToString("x2", System.Globalization.CultureInfo.InvariantCulture)));
        return "MapperForgeGeneratedExtensions_" + hash;
    }
}
